#!/bin/bash

set -e

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

# Configuration variables
DEPLOY_USER="sigmagit"
DEPLOY_DIR="/home/$DEPLOY_USER"
APP_DIR="$DEPLOY_DIR/sigmagit"
STORAGE_DIR="$DEPLOY_DIR/sigmagit-storage"
LOGS_DIR="$DEPLOY_DIR/logs"
BACKUP_DIR="$DEPLOY_DIR/backups"
SCRIPTS_DIR="$DEPLOY_DIR/scripts"
COMPOSE_FILES="-f docker-compose.yml -f docker-compose.prod.yml"

WEB_DOMAIN=""
DOCS_DOMAIN=""
GIT_REPO=""
POSTGRES_PASSWORD=""
BETTER_AUTH_SECRET=""
INTERNAL_API_SECRET=""
REGISTRY_JWT_SECRET=""
WS_TICKET_SECRET=""
MIGRATION_CREDENTIALS_KEY=""
RUNNER_REGISTRATION_SECRET=""
RESEND_API_KEY=""
SMTP_HOST=""
SMTP_PORT=""
SMTP_USER=""
SMTP_PASSWORD=""
DISCORD_BOT_TOKEN=""
DISCORD_CLIENT_ID=""
ENABLE_DISCORD="false"

log_info() {
  echo -e "${GREEN}[INFO]${NC} $1"
}

log_warn() {
  echo -e "${YELLOW}[WARN]${NC} $1"
}

log_error() {
  echo -e "${RED}[ERROR]${NC} $1"
}

check_root() {
  if [[ $EUID -ne 0 ]]; then
    log_error "This script must be run as root or with sudo"
    exit 1
  fi
}

check_ubuntu_debian() {
  if ! command -v apt-get &>/dev/null; then
    log_error "This script is designed for Ubuntu/Debian systems only"
    exit 1
  fi
}

compose_cmd() {
  su - "$DEPLOY_USER" -c "cd $APP_DIR && docker compose $COMPOSE_FILES $*"
}

# Safely assign to a named variable without eval (values may contain quotes).
set_var() {
  local var_name="$1"
  local value="$2"
  printf -v "$var_name" '%s' "$value"
}

prompt_input() {
  local prompt_text="$1"
  local default_value="$2"
  local var_name="$3"
  local input=""

  if [ -n "$default_value" ]; then
    read -r -p "$prompt_text [$default_value]: " input
    input=${input:-$default_value}
  else
    read -r -p "$prompt_text: " input
  fi

  set_var "$var_name" "$input"
}

prompt_password() {
  local prompt_text="$1"
  local var_name="$2"
  local input1=""
  local input2=""

  while true; do
    read -r -s -p "$prompt_text: " input1
    echo
    read -r -s -p "Confirm $prompt_text: " input2
    echo

    if [ "$input1" = "$input2" ]; then
      set_var "$var_name" "$input1"
      break
    else
      log_error "Passwords do not match. Please try again."
    fi
  done
}

generate_secret() {
  # 32 bytes hex = 64 chars
  if command -v openssl >/dev/null 2>&1; then
    openssl rand -hex 32
  else
    head -c 32 /dev/urandom | od -An -tx1 | tr -d ' \n'
  fi
}

update_system() {
  log_info "Updating system packages..."
  apt-get update && apt-get upgrade -y
}

create_user() {
  log_info "Creating deployment user..."

  if id "$DEPLOY_USER" &>/dev/null; then
    log_warn "User $DEPLOY_USER already exists. Skipping..."
  else
    adduser --gecos "" --disabled-password "$DEPLOY_USER"
    usermod -aG sudo "$DEPLOY_USER"
    echo "$DEPLOY_USER ALL=(ALL) NOPASSWD:/usr/bin/docker, /usr/bin/docker compose, /usr/bin/systemctl" > /etc/sudoers.d/$DEPLOY_USER
    chmod 440 /etc/sudoers.d/$DEPLOY_USER
    log_info "User $DEPLOY_USER created successfully"
  fi

  mkdir -p "$LOGS_DIR" "$BACKUP_DIR" "$SCRIPTS_DIR" "$STORAGE_DIR"
  chown -R "$DEPLOY_USER:$DEPLOY_USER" "$DEPLOY_DIR"
}

install_docker() {
  log_info "Installing Docker and Docker Compose..."

  if command -v docker &>/dev/null && docker compose version &>/dev/null; then
    log_warn "Docker is already installed. Skipping..."
  else
    curl -fsSL https://get.docker.com | sh
    log_info "Docker installed successfully"
  fi

  usermod -aG docker "$DEPLOY_USER"
  systemctl enable docker
  systemctl start docker

  docker compose version
}

clone_repository() {
  log_info "Cloning repository..."

  if [ -d "$APP_DIR" ]; then
    log_warn "Repository already exists. Pulling latest changes..."
    su - "$DEPLOY_USER" -c "cd $APP_DIR && git pull origin main"
  else
    su - "$DEPLOY_USER" -c "git clone $GIT_REPO $APP_DIR"
    log_info "Repository cloned successfully"
  fi
}

create_compose_override() {
  log_info "Creating docker-compose.prod.yml..."

  cat > "$APP_DIR/docker-compose.prod.yml" << EOF
# Generated by deploy.sh — production overrides for Docker Compose
services:
  api:
    volumes:
      - $STORAGE_DIR:/data/repos
    environment:
      STORAGE_TYPE: local
      STORAGE_LOCAL_PATH: /data/repos

  migrate:
    profiles: [tools]
    image: oven/bun:1.3.5
    working_dir: /app
    volumes:
      - .:/app
    env_file:
      - .env
    environment:
      DATABASE_URL: postgresql://sigmagit:\${POSTGRES_PASSWORD}@postgres:5432/sigmagit
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - sigmagit
    command: ["sh", "-c", "bun install && cd packages/db && bun run db:migrate"]

  discord-bot:
    profiles: [discord]
    build:
      context: .
      dockerfile: apps/discord-bot/Dockerfile
    restart: unless-stopped
    env_file:
      - .env
    environment:
      DATABASE_URL: postgresql://sigmagit:\${POSTGRES_PASSWORD}@postgres:5432/sigmagit
      REDIS_SESSION_URL: redis://redis-session:6379
      REDIS_CACHE_URL: redis://redis-cache:6379
    depends_on:
      postgres:
        condition: service_healthy
      api:
        condition: service_healthy
    networks:
      - sigmagit
EOF

  chown "$DEPLOY_USER:$DEPLOY_USER" "$APP_DIR/docker-compose.prod.yml"
  log_info "docker-compose.prod.yml created"
}

create_env_file() {
  log_info "Creating environment file..."

  # Generate independent secrets when operator leaves them blank
  if [ -z "$BETTER_AUTH_SECRET" ] || [ "${#BETTER_AUTH_SECRET}" -lt 32 ]; then
    BETTER_AUTH_SECRET="$(generate_secret)"
    log_info "Generated BETTER_AUTH_SECRET"
  fi
  if [ -z "$INTERNAL_API_SECRET" ] || [ "${#INTERNAL_API_SECRET}" -lt 32 ]; then
    INTERNAL_API_SECRET="$(generate_secret)"
    log_info "Generated INTERNAL_API_SECRET"
  fi
  if [ -z "$REGISTRY_JWT_SECRET" ] || [ "${#REGISTRY_JWT_SECRET}" -lt 32 ]; then
    REGISTRY_JWT_SECRET="$(generate_secret)"
    log_info "Generated REGISTRY_JWT_SECRET"
  fi
  if [ -z "$WS_TICKET_SECRET" ] || [ "${#WS_TICKET_SECRET}" -lt 32 ]; then
    WS_TICKET_SECRET="$(generate_secret)"
    log_info "Generated WS_TICKET_SECRET"
  fi
  if [ -z "$MIGRATION_CREDENTIALS_KEY" ] || [ "${#MIGRATION_CREDENTIALS_KEY}" -lt 16 ]; then
    MIGRATION_CREDENTIALS_KEY="$(generate_secret)"
    log_info "Generated MIGRATION_CREDENTIALS_KEY"
  fi
  if [ -z "$RUNNER_REGISTRATION_SECRET" ] || [ "${#RUNNER_REGISTRATION_SECRET}" -lt 16 ]; then
    RUNNER_REGISTRATION_SECRET="$(generate_secret)"
    log_info "Generated RUNNER_REGISTRATION_SECRET"
  fi
  if [ -z "$POSTGRES_PASSWORD" ] || [ "$POSTGRES_PASSWORD" = "sigmagit" ]; then
    POSTGRES_PASSWORD="$(generate_secret)"
    log_info "Generated strong POSTGRES_PASSWORD"
  fi

  # Ensure secrets are pairwise distinct
  if [ "$BETTER_AUTH_SECRET" = "$INTERNAL_API_SECRET" ] || \
     [ "$BETTER_AUTH_SECRET" = "$REGISTRY_JWT_SECRET" ] || \
     [ "$BETTER_AUTH_SECRET" = "$WS_TICKET_SECRET" ] || \
     [ "$INTERNAL_API_SECRET" = "$REGISTRY_JWT_SECRET" ] || \
     [ "$INTERNAL_API_SECRET" = "$WS_TICKET_SECRET" ] || \
     [ "$REGISTRY_JWT_SECRET" = "$WS_TICKET_SECRET" ]; then
    log_error "Generated secrets collided; re-run deploy.sh"
    exit 1
  fi

  # Write env with careful quoting via printf (no eval)
  umask 077
  {
    printf '%s\n' "# Generated by deploy.sh — do not commit"
    printf '%s\n' "NODE_ENV=production"
    printf 'WEB_URL=%s\n' "https://$WEB_DOMAIN"
    printf 'API_URL=%s\n' "https://$WEB_DOMAIN"
    printf 'VITE_API_URL=%s\n' "https://$WEB_DOMAIN"
    printf '%s\n' "TRUST_PROXY=true"
    printf '%s\n' "TRUSTED_PROXY_CIDRS=10.0.0.0/8,172.16.0.0/12,192.168.0.0/16"
    printf 'POSTGRES_PASSWORD=%s\n' "$POSTGRES_PASSWORD"
    printf 'DATABASE_URL=%s\n' "postgresql://sigmagit:${POSTGRES_PASSWORD}@postgres:5432/sigmagit"
    printf '%s\n' "STORAGE_TYPE=local"
    printf '%s\n' "STORAGE_LOCAL_PATH=/data/repos"
    printf 'BETTER_AUTH_SECRET=%s\n' "$BETTER_AUTH_SECRET"
    printf 'INTERNAL_API_SECRET=%s\n' "$INTERNAL_API_SECRET"
    printf 'REGISTRY_JWT_SECRET=%s\n' "$REGISTRY_JWT_SECRET"
    printf 'WS_TICKET_SECRET=%s\n' "$WS_TICKET_SECRET"
    printf 'MIGRATION_CREDENTIALS_KEY=%s\n' "$MIGRATION_CREDENTIALS_KEY"
    printf 'RUNNER_REGISTRATION_SECRET=%s\n' "$RUNNER_REGISTRATION_SECRET"
    printf '%s\n' "ENABLE_MIGRATIONS=false"
    printf '%s\n' "EMAIL_PROVIDER=resend"
    printf 'RESEND_API_KEY=%s\n' "$RESEND_API_KEY"
    printf 'SMTP_HOST=%s\n' "$SMTP_HOST"
    printf 'SMTP_PORT=%s\n' "$SMTP_PORT"
    printf 'SMTP_USER=%s\n' "$SMTP_USER"
    printf 'SMTP_PASS=%s\n' "$SMTP_PASSWORD"
    printf 'EMAIL_FROM=%s\n' "Sigmagit <noreply@$WEB_DOMAIN>"
    printf 'DISCORD_BOT_TOKEN=%s\n' "$DISCORD_BOT_TOKEN"
    printf 'DISCORD_CLIENT_ID=%s\n' "$DISCORD_CLIENT_ID"
  } > "$APP_DIR/.env"

  chmod 600 "$APP_DIR/.env"
  chown "$DEPLOY_USER:$DEPLOY_USER" "$APP_DIR/.env"
  log_info "Environment file created successfully"
}

configure_caddyfile() {
  log_info "Configuring Caddyfile for $WEB_DOMAIN..."

  if [ -f "$APP_DIR/Caddyfile" ] && [ ! -f "$APP_DIR/Caddyfile.bak" ]; then
    cp "$APP_DIR/Caddyfile" "$APP_DIR/Caddyfile.bak"
  fi

  # Prefer the checked-in hardened Caddyfile; rewrite server names only.
  if [ -f "$APP_DIR/Caddyfile" ]; then
    # Replace default site name with operator domain (safe sed, no eval)
    sed -i.bak-domain \
      -e "s/^sigmagit\\.com {/$WEB_DOMAIN {/" \
      -e "s/^docs\\.sigmagit\\.com {/${DOCS_DOMAIN:-docs.$WEB_DOMAIN} {/" \
      "$APP_DIR/Caddyfile" || true
    # Ensure security headers block exists (checked-in file already has them)
    log_info "Using repository Caddyfile with domain substitution"
  else
    log_error "Caddyfile missing from repository clone"
    exit 1
  fi

  chown "$DEPLOY_USER:$DEPLOY_USER" "$APP_DIR/Caddyfile"
  log_info "Caddyfile configured"
}

build_and_start() {
  log_info "Building and starting services with Docker Compose..."

  compose_cmd "build"

  if [ "$ENABLE_DISCORD" = "true" ]; then
    compose_cmd "--profile discord up -d"
  else
    compose_cmd "up -d"
  fi

  log_info "Services started"
}

run_migrations() {
  log_info "Running database migrations..."
  compose_cmd "--profile tools run --rm migrate"
  log_info "Migrations completed"
}

wait_for_healthy() {
  log_info "Waiting for PostgreSQL to become ready..."
  local retries=30
  while [ $retries -gt 0 ]; do
    if compose_cmd "exec -T postgres pg_isready -U sigmagit -d sigmagit" >/dev/null 2>&1; then
      log_info "PostgreSQL is ready"
      return 0
    fi
    retries=$((retries - 1))
    sleep 2
  done
  log_warn "Timed out waiting for PostgreSQL — check: cd $APP_DIR && docker compose $COMPOSE_FILES ps"
}

configure_firewall() {
  log_info "Configuring firewall..."

  if ! command -v ufw &>/dev/null; then
    apt-get install -y ufw
  fi

  ufw allow 22/tcp
  ufw allow 80/tcp
  ufw allow 443/tcp
  echo "y" | ufw enable

  log_info "Firewall configured"
}

create_backup_script() {
  log_info "Creating backup script..."

  cat > "$SCRIPTS_DIR/backup.sh" << EOF
#!/bin/bash
set -e
BACKUP_DIR="$BACKUP_DIR"
DATE=\$(date +%Y%m%d_%H%M%S)
BACKUP_FILE="\$BACKUP_DIR/sigmagit_\$DATE.sql"

mkdir -p "\$BACKUP_DIR"

cd "$APP_DIR"
docker compose $COMPOSE_FILES exec -T postgres \\
  pg_dump -U sigmagit sigmagit > "\$BACKUP_FILE"

gzip "\$BACKUP_FILE"
find "\$BACKUP_DIR" -name "*.sql.gz" -mtime +7 -delete

echo "Backup completed: \${BACKUP_FILE}.gz"
EOF

  chmod +x "$SCRIPTS_DIR/backup.sh"
  chown "$DEPLOY_USER:$DEPLOY_USER" "$SCRIPTS_DIR/backup.sh"

  (crontab -l -u "$DEPLOY_USER" 2>/dev/null || true; echo "0 2 * * * $SCRIPTS_DIR/backup.sh >> $LOGS_DIR/backup.log 2>&1") | crontab -u "$DEPLOY_USER" -

  log_info "Backup script created and scheduled"
}

create_update_script() {
  log_info "Creating update script..."

  cat > "$SCRIPTS_DIR/update.sh" << EOF
#!/bin/bash
set -e
cd "$APP_DIR"
git pull origin main
docker compose $COMPOSE_FILES build
docker compose $COMPOSE_FILES up -d
docker compose $COMPOSE_FILES --profile tools run --rm migrate
echo "Update complete"
EOF

  chmod +x "$SCRIPTS_DIR/update.sh"
  chown "$DEPLOY_USER:$DEPLOY_USER" "$SCRIPTS_DIR/update.sh"
  log_info "Update script created at $SCRIPTS_DIR/update.sh"
}

print_summary() {
  log_info "Deployment completed successfully!"
  echo
  echo "=== Summary ==="
  echo "Web URL: https://$WEB_DOMAIN"
  echo "API URL: https://$WEB_DOMAIN/api"
  if [ -n "$DOCS_DOMAIN" ]; then
    echo "Docs URL: https://$DOCS_DOMAIN"
  fi
  echo "User: $DEPLOY_USER"
  echo "App Directory: $APP_DIR"
  echo "Storage Directory: $STORAGE_DIR"
  echo
  echo "=== Docker Compose Commands ==="
  echo "Status:  cd $APP_DIR && docker compose $COMPOSE_FILES ps"
  echo "Logs:    cd $APP_DIR && docker compose $COMPOSE_FILES logs -f"
  echo "Restart: cd $APP_DIR && docker compose $COMPOSE_FILES restart"
  echo "Update:  $SCRIPTS_DIR/update.sh"
  echo "Backup:  $SCRIPTS_DIR/backup.sh"
  if [ "$ENABLE_DISCORD" = "true" ]; then
    echo "Discord bot is enabled (discord profile)"
  else
    echo "Discord bot disabled — set token and run: docker compose $COMPOSE_FILES --profile discord up -d"
  fi
  echo
}

main() {
  echo "==================================="
  echo "  Sigmagit Docker Compose Deploy  "
  echo "==================================="
  echo

  check_root
  check_ubuntu_debian

  log_info "Please provide the following configuration:"
  prompt_input "Git repository URL" "" GIT_REPO
  prompt_input "Primary domain (e.g., sigmagit.com)" "" WEB_DOMAIN
  prompt_input "Docs domain (optional, press Enter to skip)" "" DOCS_DOMAIN
  prompt_password "PostgreSQL password (blank to auto-generate strong secret)" POSTGRES_PASSWORD
  log_info "Auth/crypto secrets will be auto-generated if left blank (recommended)"
  prompt_input "Better Auth Secret (blank to auto-generate)" "" BETTER_AUTH_SECRET
  prompt_input "Internal API Secret (blank to auto-generate)" "" INTERNAL_API_SECRET
  prompt_input "Registry JWT Secret (blank to auto-generate)" "" REGISTRY_JWT_SECRET
  prompt_input "WebSocket Ticket Secret (blank to auto-generate)" "" WS_TICKET_SECRET
  prompt_input "Migration Credentials Key (blank to auto-generate)" "" MIGRATION_CREDENTIALS_KEY
  prompt_input "Runner Registration Secret (blank to auto-generate)" "" RUNNER_REGISTRATION_SECRET
  prompt_input "Resend API Key (optional)" "" RESEND_API_KEY
  prompt_input "SMTP Host (optional)" "smtp.gmail.com" SMTP_HOST
  prompt_input "SMTP Port (optional)" "587" SMTP_PORT
  prompt_input "SMTP User (optional)" "" SMTP_USER
  prompt_input "SMTP Password (optional)" "" SMTP_PASSWORD
  prompt_input "Discord Bot Token (optional)" "" DISCORD_BOT_TOKEN
  prompt_input "Discord Client ID (optional)" "" DISCORD_CLIENT_ID

  if [ -n "$DISCORD_BOT_TOKEN" ] && [ -n "$DISCORD_CLIENT_ID" ]; then
    ENABLE_DISCORD="true"
  fi

  echo
  log_warn "Starting deployment process..."
  echo

  update_system
  create_user
  install_docker
  clone_repository
  create_compose_override
  create_env_file
  configure_caddyfile
  build_and_start
  wait_for_healthy
  run_migrations
  configure_firewall
  create_backup_script
  create_update_script
  print_summary
}

main
